### PR TITLE
use Vercel Build Output API (v3) for Vercel adapter, support ESM, add examples, ...

### PR DESCRIPTION
**Pull request by Vexcited**
Hello !

Recently, I emailed Vercel support team because I had an issue supporting ESM on their service with this Vite plugin.

I thought it was a problem from them but I was wrong. So they told me to use the Build Output v3. So here is my implementation ! I hope you will merge this because it would be very cool for us so we can use packages like `got` directly in the API routes.

Also, this is not the only thing I did in this PR. I also added a `examples` folder with 3 examples:
- `with-node`
- `with-node-esm`
- `with-vercel`

I made them so I can easily test my integration with each of them.

Yes, I also tested Node because I implemented ESM support when the app have `"type": "module"` in its `package.json`.

Also, I did some changes on the exports so there's an export of `vite-plugin-mix` for ESM and CJS. Why ? Because when you add `"type": "module"` in your `package.json`, it simply doesn't recognize the functions anymore (so now it's fixed)

Hope I didn't messed up anything ! Oh, by the way I didn't ran any eslint or prettier on my code so please do it if you want to !

~ Tell me if you have any question about my code !

#### Fixed Issues
- [x] #33
- [x] #31

### CODE REVIEW

**Comment by egoist** [comment]
it seems our vercel adapter implementation doesn't work with monorepo, so I'm considering just dropping the vercel adapter and let the user create a `vercel.json` config by themselves and use `@vercel/node` instead.

**Comment by Vexcited** [comment]
Thanks you for seeing this !

Uhm- that's kinda sad but if it's the only way to do it...
That's not a bad idea after all, you should be right.

**Comment by egoist** [comment]
A custom builder is required for proper Vercel support, like this one for Remix: https://github.com/vercel/vercel/tree/main/packages/remix

**Comment by egoist** [comment]
`vercel dev` also works pretty well now, you can just create a `api/index.js` and run `vercel dev` 🤔

**Comment by Vexcited** [comment]
Yes `vercel dev` could work too but it would require to people to install the Vercel CLI and also link it to their account.

Even if it's only the `dev` command they still need to link it, if I remember well ?

**Pull request closed without merging**
